spring:
  docker:
    compose:
      file: compose.yaml
      enabled: ${FMS_ENABLE_COMPOSE:true}
      lifecycle-management: start_only
  jpa:
    open-in-view: false
    show-sql: ${FMS_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: ${FMS_DATABASE_USER:file_management_system_user}
    password: ${FMS_DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${FMS_DATABASE_HOST:localhost}:${FMS_DATABASE_PORT:3350}/${FMS_DATABASE_NAME:file_management_system}
  application:
    name: file-management-system
server:
  port: ${FMS_PORT:8080}
  address: 0.0.0.0
  servlet:
    context-path: /file-management-system/api/
management:
  tracing:
    propagation:
      type: w3c
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
      enabled: true
  zipkin:
    tracing:
      endpoint: ${FMS_ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
